<?php

$labels = array(
  'name' => _x('Countries', 'General name', 'gourmar'),
  'singular_name' => _x('Country', 'Singular name', 'gourmar'),
  'menu_name' => __('Countries', 'gourmar'),
  'name_admin_bar' => __('Country', 'gourmar'),
  'archives' => __('Item Archives', 'gourmar'),
  'attributes' => __('Item Attributes', 'gourmar'),
  'parent_item_colon' => __('Parent Item:', 'gourmar'),
  'all_items' => __('All Countries', 'gourmar'),
  'add_new_item' => __('Add new Country', 'gourmar'),
  'add_new' => __('Add new', 'gourmar'),
  'new_item' => __('new Country', 'gourmar'),
  'edit_item' => __('Edit Country', 'gourmar'),
  'update_item' => __('Update Country', 'gourmar'),
  'view_item' => __('View Country', 'gourmar'),
  'view_items' => __('View Countries', 'gourmar'),
  'search_items' => __('Search Countries', 'gourmar'),
  'not_found' => __('No Countries found', 'gourmar'),
  'not_found_in_trash' => __('No Countries found in the trash', 'gourmar'),
  'featured_image' => __('Featured image', 'gourmar'),
  'set_featured_image' => __('Add featured image', 'gourmar'),
  'remove_featured_image' => __('Remove featured image', 'gourmar'),
  'use_featured_image' => __('Use as featured image', 'gourmar'),
  'insert_into_item' => __('Insert to Countries', 'gourmar'),
  'uploaded_to_this_item' => __('Upload to Country', 'gourmar'),
  'items_list' => __('List of Countries', 'gourmar'),
  'items_list_navigation' => __('Navigate to list of Countries', 'gourmar'),
  'filter_items_list' => __('Filter list of Countries', 'gourmar'),
);
$args = array(
  'label' => __('Country', 'gourmar'),
  'description' => __('Country description', 'gourmar'),
  'labels' => $labels,
  'supports' => array('title'),
  //'taxonomies' => array('country-category'),
  'hierarchical' => false,
  'public' => true,
  'show_ui' => true,
  'show_in_menu' => true,
  'menu_position' => 7,
  'can_export' => true,
  'has_archive' => true,
  'exclude_from_search' => true,
  'publicly_queryable' => true,
  'map_meta_cap' => true,
  'query_var' => true,
  'rewrite' => array('slug' => 'country'),
  'menu_icon' => 'dashicons-admin-site',
  'show_in_rest' => true,
  'rest_base' => 'country'
);
register_post_type('country', $args);

