<?php

$labels = array(
  'name' => _x('Providers', 'General name', 'gourmar'),
  'singular_name' => _x('Provider', 'Singular name', 'gourmar'),
  'menu_name' => __('Providers', 'gourmar'),
  'name_admin_bar' => __('Provider', 'gourmar'),
  'archives' => __('Item Archives', 'gourmar'),
  'attributes' => __('Item Attributes', 'gourmar'),
  'parent_item_colon' => __('Parent Item:', 'gourmar'),
  'all_items' => __('All Providers', 'gourmar'),
  'add_new_item' => __('Add new Provider', 'gourmar'),
  'add_new' => __('Add new', 'gourmar'),
  'new_item' => __('new Provider', 'gourmar'),
  'edit_item' => __('Edit Provider', 'gourmar'),
  'update_item' => __('Update Provider', 'gourmar'),
  'view_item' => __('View Provider', 'gourmar'),
  'view_items' => __('View Providers', 'gourmar'),
  'search_items' => __('Search Providers', 'gourmar'),
  'not_found' => __('No Providers found', 'gourmar'),
  'not_found_in_trash' => __('No Providers found in the trash', 'gourmar'),
  'featured_image' => __('Featured image', 'gourmar'),
  'set_featured_image' => __('Add featured image', 'gourmar'),
  'remove_featured_image' => __('Remove featured image', 'gourmar'),
  'use_featured_image' => __('Use as featured image', 'gourmar'),
  'insert_into_item' => __('Insert to Providers', 'gourmar'),
  'uploaded_to_this_item' => __('Upload to Provider', 'gourmar'),
  'items_list' => __('List of Providers', 'gourmar'),
  'items_list_navigation' => __('Navigate to list of Providers', 'gourmar'),
  'filter_items_list' => __('Filter list of Providers', 'gourmar'),
);
$args = array(
  'label' => __('Provider', 'gourmar'),
  'description' => __('Provider description', 'gourmar'),
  'labels' => $labels,
  'supports' => array('title'),
  //'taxonomies' => array('Provider-category'),
  'hierarchical' => false,
  'public' => true,
  'show_ui' => true,
  'show_in_menu' => true,
  'menu_position' => 7,
  'can_export' => true,
  'has_archive' => true,
  'exclude_from_search' => true,
  'publicly_queryable' => true,
  'map_meta_cap' => true,
  'query_var' => true,
  'rewrite' => array('slug' => 'provider'),
  'menu_icon' => 'dashicons-food',
  'show_in_rest' => true,
  'rest_base' => 'provider'
);
register_post_type('Provider', $args);

